"""create initial schema

Revision ID: 711c33ee9f69
Revises: 
Create Date: 2026-05-24 07:04:48.210215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711c33ee9f69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_table('contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', 'name', name='uq_contexts_user_type_name')
    )
    op.create_index('ix_contexts_user_id', 'contexts', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_created_at', 'feedback', ['created_at'], unique=False)
    op.create_index('ix_feedback_is_read', 'feedback', ['is_read'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_name')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_templates_is_sample', 'templates', ['is_sample'], unique=False)
    op.create_index('ix_templates_user_id', 'templates', ['user_id'], unique=False)
    op.create_table('ai_query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=True),
    sa.Column('prompt_preview', sa.String(length=200), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_query_logs_context_id'), 'ai_query_logs', ['context_id'], unique=False)
    op.create_index('ix_ai_query_logs_created_at', 'ai_query_logs', ['created_at'], unique=False)
    op.create_index('ix_ai_query_logs_user_created', 'ai_query_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_query_logs_user_id'), 'ai_query_logs', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('time_window_start', sa.Date(), nullable=True),
    sa.Column('time_window_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_context_id'), 'chat_sessions', ['context_id'], unique=False)
    op.create_index('ix_chat_sessions_user_created', 'chat_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('content_encrypted', sa.Text(), nullable=False),
    sa.Column('embedding_status', sa.String(length=20), nullable=False),
    sa.Column('date_type', sa.String(length=10), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("date_type IN ('daily', 'weekly', 'custom')", name='ck_log_entries_date_type'),
    sa.CheckConstraint("embedding_status IN ('pending', 'embedded', 'failed')", name='ck_log_entries_embedding_status'),
    sa.CheckConstraint('date_end >= date_start', name='ck_log_entries_date_range'),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_context_id'), 'log_entries', ['context_id'], unique=False)
    op.create_index('ix_log_entries_embedding_status', 'log_entries', ['embedding_status'], unique=False, postgresql_where='is_deleted = false')
    op.create_index('ix_log_entries_user_context_dates', 'log_entries', ['user_id', 'context_id', 'date_start', 'date_end'], unique=False, postgresql_where='is_deleted = false')
    op.create_index('ix_log_entries_user_date_start', 'log_entries', ['user_id', 'date_start'], unique=False, postgresql_where='is_deleted = false')
    op.create_index('ix_log_entries_user_deleted', 'log_entries', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_log_entries_user_id'), 'log_entries', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_chat_messages_role'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_session_id'), 'chat_messages', ['chat_session_id'], unique=False)
    op.create_index('ix_chat_messages_session_created', 'chat_messages', ['chat_session_id', 'created_at'], unique=False)
    op.create_table('log_entry_tags',
    sa.Column('log_entry_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['log_entry_id'], ['log_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_entry_id', 'tag_id')
    )
    op.create_index('ix_log_entry_tags_tag_id', 'log_entry_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_entry_tags_tag_id', table_name='log_entry_tags')
    op.drop_table('log_entry_tags')
    op.drop_index('ix_chat_messages_session_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_chat_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_log_entries_user_id'), table_name='log_entries')
    op.drop_index('ix_log_entries_user_deleted', table_name='log_entries')
    op.drop_index('ix_log_entries_user_date_start', table_name='log_entries', postgresql_where='is_deleted = false')
    op.drop_index('ix_log_entries_user_context_dates', table_name='log_entries', postgresql_where='is_deleted = false')
    op.drop_index('ix_log_entries_embedding_status', table_name='log_entries', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_log_entries_context_id'), table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index('ix_chat_sessions_user_created', table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_context_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_ai_query_logs_user_id'), table_name='ai_query_logs')
    op.drop_index('ix_ai_query_logs_user_created', table_name='ai_query_logs')
    op.drop_index('ix_ai_query_logs_created_at', table_name='ai_query_logs')
    op.drop_index(op.f('ix_ai_query_logs_context_id'), table_name='ai_query_logs')
    op.drop_table('ai_query_logs')
    op.drop_index('ix_templates_user_id', table_name='templates')
    op.drop_index('ix_templates_is_sample', table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index('ix_feedback_is_read', table_name='feedback')
    op.drop_index('ix_feedback_created_at', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_contexts_user_id', table_name='contexts')
    op.drop_table('contexts')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
